version: '3'
services:
  web:
    image: webimage
    build: .
    ports:
      - "9000-9001:3000"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
  redis:
    image: redis
    command: ["redis-server", "--bind", "redis", "--port", "6379"]